import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  header: { backgroundColor: '#2c3e50', paddingTop: 50, paddingBottom: 25, paddingHorizontal: 20, borderBottomLeftRadius: 30, borderBottomRightRadius: 30, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 5, elevation: 8 },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#ecf0f1', marginBottom: 5 },
  summaryCard: { backgroundColor: 'rgba(255, 255, 255, 0.15)', paddingVertical: 15, paddingHorizontal: 30, borderRadius: 20, marginTop: 10, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
  summaryLabel: { fontSize: 12, color: '#bdc3c7', textTransform: 'uppercase', letterSpacing: 1 },
  summaryValue: { fontSize: 32, fontWeight: '800', color: '#e74c3c' },
  kcalUnit: { fontSize: 16, color: '#ecf0f1', fontWeight: '500' },
  listContainer: { flex: 1, paddingHorizontal: 20, paddingTop: 20 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#34495e', marginBottom: 15, marginLeft: 5 },
  emptyState: { alignItems: 'center', marginTop: 50, opacity: 0.6 },
  emptyText: { fontSize: 16, color: '#7f8c8d', marginTop: 10 },
  logItem: { flexDirection: 'row', backgroundColor: '#fff', padding: 15, borderRadius: 16, marginBottom: 12, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 3, elevation: 3 },
  iconContainer: { width: 45, height: 45, backgroundColor: '#fef5e7', borderRadius: 12, justifyContent: 'center', alignItems: 'center', marginRight: 15 },
  infoContainer: { flex: 1 },
  foodName: { fontSize: 16, fontWeight: '600', color: '#2d3436' },
  foodDate: { fontSize: 12, color: '#b2bec3', marginTop: 3 },
  calorieBadge: { backgroundColor: '#eafaf1', paddingVertical: 5, paddingHorizontal: 10, borderRadius: 8 },
  calorieText: { fontSize: 14, fontWeight: '700', color: '#27ae60' },
  fabContainer: { position: 'absolute', bottom: 30, alignSelf: 'center' },
  fab: { width: 70, height: 70, borderRadius: 35, backgroundColor: '#3498db', justifyContent: 'center', alignItems: 'center', shadowColor: '#3498db', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.4, shadowRadius: 8, elevation: 10 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: '85%', backgroundColor: '#fff', borderRadius: 25, padding: 25, alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.25, shadowRadius: 10, elevation: 15 },
  modalImage: { width: 200, height: 200, borderRadius: 15, marginBottom: 20 },
  modalTitle: { fontSize: 22, fontWeight: 'bold', color: '#2c3e50', textAlign: 'center' },
  modalCalories: { fontSize: 18, color: '#e74c3c', fontWeight: '600', marginVertical: 10 },
  modalPortion: { fontSize: 14, color: '#95a5a6', marginBottom: 25 },
  modalButtons: { flexDirection: 'row', width: '100%', justifyContent: 'space-between' },
  cancelButton: { flex: 1, paddingVertical: 15, backgroundColor: '#ecf0f1', borderRadius: 12, marginRight: 10, alignItems: 'center' },
  cancelButtonText: { color: '#7f8c8d', fontWeight: 'bold', fontSize: 16 },
  saveButton: { flex: 1, paddingVertical: 15, backgroundColor: '#2ecc71', borderRadius: 12, marginLeft: 10, alignItems: 'center' },
  saveButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
});